### ISSUE TITLE
Trakt.tv v1 API is not working anymore.

### ISSUE THREAD

**Issue by gilabrantes** [adam-h/myepisodes_export#6]
Trakt.tv updated their API with a v2 using OAuth.
Are there any plans for supporting this?

**Comment by adam-h** [comment]
Sorry, not from me as I migrated a couple of years ago and put this up incase it is useful to others. Will accept pull requests to fix it though.

**Comment by gilabrantes** [comment]
Makes sense, maybe I'll take the time to do it.

Thanks!
